FROM postgres:17-alpine

RUN apk add --no-cache \
    git \
    build-base \
    postgresql-dev

RUN git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git /tmp/pgvector && \
    cd /tmp/pgvector && \
    PG_CONFIG=/usr/local/bin/pg_config make && \
    PG_CONFIG=/usr/local/bin/pg_config make install && \
    cd / && \
    rm -rf /tmp/pgvector

RUN apk del git build-base postgresql-dev
